services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: azsx0123456
      POSTGRES_USER: root
      POSTGRES_DB: simple_bank
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1234:1234
    depends_on:
      - postgres
    environment:
      DB_SOURCE: postgresql://root:azsx0123456@postgres:5432/simple_bank?sslmode=disable
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]
volumes:
  postgres_data:
